### ISSUE TITLE
rewrite

### ISSUE THREAD

**Issue by aeosynth** [aeosynth/draft#79]
- [x] #33 chat in draft queues
- [x] #37 ditch the cloud
- [x] #52 host options (at least kicking)
- [x] #67 stacked cards
- [x] #77 beep bug
- [ ] stacked cards mobile view
- [ ] fix regressions

the stack will probably be [esnext](https://github.com/square/esnext) + [react](https://github.com/facebook/react). i want destructuring merged into esnext before the rewrite, but until then, i could port the existing design

edit: [react 0.11](http://facebook.github.io/react/blog/2014/07/17/react-v0.11.html) supports harmony features, including destructuring
